# 1\. 异常

异常通常用于处理逻辑上可能发生的错误，在 C++98 中为我们提供了一套完善的异常处理机制，我们可以直接在程序中将各种类型的异常抛出，从而强制终止程序的运行。

## 1.1 基本语法

关于异常的基本语法如下：

![2016314153429533.jpg (577×329)](res/08.noexcept.assets/2016314153429533-1684152528432-69.jpg)

c++

<table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="type">int</span> <span class="title">main</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>{ </span><br><span class="line">    <span class="keyword">try</span></span><br><span class="line">    {</span><br><span class="line">        <span class="keyword">throw</span> <span class="number">-1</span>; </span><br><span class="line">    } </span><br><span class="line">    <span class="built_in">catch</span> (<span class="type">int</span> e)</span><br><span class="line">    { </span><br><span class="line">        cout &lt;&lt; <span class="string">"int exception, value: "</span> &lt;&lt; e &lt;&lt; endl; </span><br><span class="line">    } </span><br><span class="line">    cout &lt;&lt; <span class="string">"That's ok!"</span> &lt;&lt; endl; </span><br><span class="line">    <span class="keyword">return</span> <span class="number">0</span>; </span><br><span class="line">}</span><br></pre></td></tr></tbody></table>

异常被抛出后，从进入 try 块起，到异常被抛掷前，这期间在栈上构造的所有对象，都会被自动析构。析构的顺序与构造的顺序相反。这一过程称为栈的解旋。

## 1.2 异常接口声明

为了加强程序的可读性，可以在函数声明中列出可能抛出的所有异常类型，常用的有如下三种书写方式：

1. 显示指定可以抛出的异常类型
   
    c++
    
    <table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">struct</span> <span class="title class_">MyException</span></span><br><span class="line">{</span><br><span class="line">    <span class="built_in">MyException</span>(string s) :<span class="built_in">msg</span>(s) {}</span><br><span class="line">    string msg;</span><br><span class="line">};</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="type">double</span> <span class="title">divisionMethod</span><span class="params">(<span class="type">int</span> a, <span class="type">int</span> b)</span> <span class="title">throw</span><span class="params">(MyException, <span class="type">int</span>)</span></span></span><br><span class="line"><span class="function"></span>{</span><br><span class="line">    <span class="keyword">if</span> (b == <span class="number">0</span>)</span><br><span class="line">    {</span><br><span class="line">        <span class="keyword">throw</span> <span class="built_in">MyException</span>(<span class="string">"division by zero!!!"</span>);</span><br><span class="line">        <span class="comment">// throw 100;</span></span><br><span class="line">    }</span><br><span class="line">    <span class="keyword">return</span> a / b;</span><br><span class="line">}</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="type">int</span> <span class="title">main</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>{</span><br><span class="line">    <span class="keyword">try</span></span><br><span class="line">    {	</span><br><span class="line">        <span class="type">double</span> v = <span class="built_in">divisionMethod</span>(<span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        cout &lt;&lt; <span class="string">"value: "</span> &lt;&lt; v &lt;&lt; endl;</span><br><span class="line">    }</span><br><span class="line">    <span class="built_in">catch</span> (<span class="type">int</span> e)</span><br><span class="line">    {</span><br><span class="line">        cout &lt;&lt; <span class="string">"catch except: "</span>  &lt;&lt; e &lt;&lt; endl;</span><br><span class="line">    }</span><br><span class="line">    <span class="built_in">catch</span> (MyException e)</span><br><span class="line">    {</span><br><span class="line">        cout &lt;&lt; <span class="string">"catch except: "</span> &lt;&lt; e.msg &lt;&lt; endl;</span><br><span class="line">    }</span><br><span class="line">    <span class="keyword">return</span> <span class="number">0</span>;</span><br><span class="line">}</span><br></pre></td></tr></tbody></table>
    
    第 7 行代码在 `divisionMethod` 函数后添加了 `throw` 异常接口声明，其参数表示可以抛出的异常类型，分别为 int 和 MyException 类型。
    
2. 抛出任意异常类型
   
    c++
    
    <table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">struct</span> <span class="title class_">MyException</span></span><br><span class="line">{</span><br><span class="line">    <span class="built_in">MyException</span>(string s) :<span class="built_in">msg</span>(s) {}</span><br><span class="line">    string msg;</span><br><span class="line">};</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="type">double</span> <span class="title">divisionMethod</span><span class="params">(<span class="type">int</span> a, <span class="type">int</span> b)</span></span></span><br><span class="line"><span class="function"></span>{</span><br><span class="line">    <span class="keyword">if</span> (b == <span class="number">0</span>)</span><br><span class="line">    {</span><br><span class="line">        <span class="keyword">throw</span> <span class="built_in">MyException</span>(<span class="string">"division by zero!!!"</span>);</span><br><span class="line">        <span class="comment">// throw 100;</span></span><br><span class="line">    }</span><br><span class="line">    <span class="keyword">return</span> a / b;</span><br><span class="line">}</span><br></pre></td></tr></tbody></table>
    
    第 7 行代码在 `divisionMethod 没有添加异常接口声明`，表示在该函数中`可以抛出任意类型的异常`。
    
3. 不抛出任何异常
   
    c++
    
    <table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">struct</span> <span class="title class_">MyException</span></span><br><span class="line">{</span><br><span class="line">    <span class="built_in">MyException</span>(string s) :<span class="built_in">msg</span>(s) {}</span><br><span class="line">    string msg;</span><br><span class="line">};</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="type">double</span> <span class="title">divisionMethod</span><span class="params">(<span class="type">int</span> a, <span class="type">int</span> b)</span> <span class="title">throw</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>{</span><br><span class="line">    <span class="keyword">if</span> (b == <span class="number">0</span>)</span><br><span class="line">    {</span><br><span class="line">        cout &lt;&lt; <span class="string">"division by zero!!!"</span> &lt;&lt; endl;</span><br><span class="line">    }</span><br><span class="line">    <span class="keyword">return</span> a / b;</span><br><span class="line">}</span><br></pre></td></tr></tbody></table>
    
    第 7 行代码在 `divisionMethod` 函数后添加了 `throw` 异常接口声明，其`参数列表为空`，表示该函数==不允许抛出异常==。
    

温馨提示：以上程序在 VS 上的测试结果和在 Linux 上基于 G++ 的测试结果是不同的，如果违反了规则 VS 只会给出警告，而 G++ 则会直接终止程序的运行。（PS：VS 使用的不是 G++ 编译器）

1. throw声明
   1. void GetTag() throw(int);                     // 表示只抛出int类型异常
   2. void GetTag() throw(int，char);         // 表示抛出in，char类型异常
      1. 可以自定义抛出异常类型
   3. void GetTag() throw();                         // 表示不会抛出任何类型异常
      1. 但若在函数中尝试抛出异常，若直接将常量进行抛出，如throw（1），则报错，若抛出变量int i，throw（i）则可抛出，==无法抛出字面量常量可抛出变量==
      2. ==throw（）并不严格，若使用noexcept，则无论什么异常都无法抛出==
   4. void GetTag() throw(...);                      // 表示抛出任何类型异常

# 2\. noexcept

上面的例子中，在 `divisionMethod` 函数声明之后，我们定义了一个动态异常声明 `throw(MyException, int)`，该声明指出了 `divisionMethod` 可能抛出的异常的类型。事实上，该特性很少被使用，因此在 C++11 中被弃用了 ，而表示函数不会抛出异常的动态异常声明 `throw()` 也被新的 noexcept 异常声明所取代。 

noexcept 形如其名， 表示其修饰的函数不会抛出异常 。不过与 \`throw ()\` 动态异常声明不同的是，\`在 C++11 中如果 noexcept 修饰的函数抛出了异常，编译器可以选择直接调用 std::terminate () 函数来终止程序的运行，这比基于异常机制的 throw () 在效率上会高一些\`。这是因为异常机制会带来一些额外开销，比如函数抛出异常，会导致函数栈被依次地展开（栈解旋），并自动调用析构函数释放栈上的所有对象。

因此对于不会抛出异常的函数我们可以这样写:

c++

<table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="type">double</span> <span class="title">divisionMethod</span><span class="params">(<span class="type">int</span> a, <span class="type">int</span> b)</span> <span class="keyword">noexcept</span></span></span><br><span class="line"><span class="function"></span>{</span><br><span class="line">    <span class="keyword">if</span> (b == <span class="number">0</span>)</span><br><span class="line">    {</span><br><span class="line">        cout &lt;&lt; <span class="string">"division by zero!!!"</span> &lt;&lt; endl;</span><br><span class="line">        <span class="keyword">return</span> <span class="number">-1</span>;</span><br><span class="line">    }</span><br><span class="line">    <span class="keyword">return</span> a / b;</span><br><span class="line">}</span><br></pre></td></tr></tbody></table>

从语法上讲，`noexcept` 修饰符有两种形式：

1. 简单地在函数声明后加上 noexcept 关键字
   
2. 可以接受一个常量表达式作为参数，如下所示∶
   
    c++
    
    <table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="type">double</span> <span class="title">divisionMethod</span><span class="params">(<span class="type">int</span> a, <span class="type">int</span> b)</span> <span class="title">noexcept</span><span class="params">(常量表达式)</span></span>;</span><br></pre></td></tr></tbody></table>
    
    常量表达式的结果会被转换成一个 bool 类型的值：
    
    - 值为 true，表示函数不会抛出异常
    - 值为 false，表示有可能抛出异常这里
    - 不带常量表达式的 noexcept 相当于声明了 noexcept（true），即不会抛出异常。